#pragma once
#include "dmg07.hpp"
#include "dmg07x4.hpp"
#include "hack_4p_tetris.hpp"
#include "hack_4p_kwirk.hpp"
#pragma once
#include "barcodeboy.hpp"
#include "faceball2000_cable.hpp"
#include "power_antenna.hpp"